Update repo template files

diff --git a/.github/workflows/BUILD.yml b/.github/workflows/BUILD.yml
--- a/.github/workflows/BUILD.yml
+++ b/.github/workflows/BUILD.yml
@@ -2,14 +2,13 @@ name: Build
 
 on:
   workflow_dispatch:
-    branches: [ main ]
   push:
   pull_request:
 
 jobs:
   build:
+    name: Build
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
@@ -38,3 +37,31 @@ jobs:
           name: ${{ github.event.repository.name }}__extract_this_zip
           path: ./dist/*
           retention-days: 15
+
+  validate-resx-files:
+    name: Validate resx files
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
+      - name: Setup xmllint
+        run: |
+          if ! command -v xmllint &> /dev/null
+          then
+            sudo apt-get update
+            sudo apt-get install -y libxml2-utils
+          fi
+        shell: bash
+      - name: Check resx files contain valid xml
+        run: |
+          shopt -s globstar
+          for resx_file in $(/bin/ls ./**/*.resx)
+          do
+            if xmllint --noout "$resx_file" > /dev/null 2>&1 ;
+            then
+              echo "Valid: $resx_file"
+            else
+              echo "Invalid: $resx_file" && exit 1
+            fi
+          done
+        shell: bash
